/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Login.Login;
import calculadora.calculadora;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import referenciales.*;

/**
 *
 * @author Alex
 */

public class menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form menu_principal
     */
    //Metodo para abrir los archivos pdf
    public void abrirarchivo(String archivo){
        try{
            File path = new File(archivo);
            Desktop.getDesktop().open(path);
        }catch (IOException ex){
            System.out.println(ex);
            JOptionPane.showMessageDialog(null,"No se encontro el archivo","Error",0);
        }
    }
    //Metodo para ejecutar archivos .exe
    public void ejecutar(){
        try {
            Runtime correr = Runtime.getRuntime();
            
            String cmd = "C:/Windows/System32/cmd.exe";
            
            String cmd2 = "C:/Users/Alex/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/System Tools/Símbolo del sistema";
            
            Process process = correr.exec(cmd);
            
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    java.util.Date fecha = new Date();
    public menu_principal() {
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/login.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        barra_menuPrincipal = new javax.swing.JMenuBar();
        jmenuUsuario = new javax.swing.JMenu();
        mitemcambiarUsuario = new javax.swing.JMenuItem();
        jmenuReferenciales = new javax.swing.JMenu();
        mitem_ciudad = new javax.swing.JMenuItem();
        mitem_pais = new javax.swing.JMenuItem();
        mitem_registrosdatos = new javax.swing.JMenuItem();
        jmenuCalculadora = new javax.swing.JMenu();
        mitem_calculadora = new javax.swing.JMenuItem();
        jmenuMateriales = new javax.swing.JMenu();
        jmenuJframeM = new javax.swing.JMenu();
        jmenuJframeI = new javax.swing.JMenu();
        mitemcuadrosVerificacion = new javax.swing.JMenuItem();
        mitembotonesOpcion = new javax.swing.JMenuItem();
        mitemlistas = new javax.swing.JMenuItem();
        mitemcomboss = new javax.swing.JMenuItem();
        mitemlistaModelos = new javax.swing.JMenuItem();
        mitemcombosModelos = new javax.swing.JMenuItem();
        mitemtoggleButtons = new javax.swing.JMenuItem();
        mitemsliderss = new javax.swing.JMenuItem();
        mitemSpinners = new javax.swing.JMenuItem();
        mitembarraDespl = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmenuJframeII = new javax.swing.JMenu();
        mitembarraMenus = new javax.swing.JMenuItem();
        mitembarraHerramientas = new javax.swing.JMenuItem();
        mitemmenuEmergentes = new javax.swing.JMenuItem();
        mitemfileChoosers = new javax.swing.JMenuItem();
        mitemPanelesdesplazamiento = new javax.swing.JMenuItem();
        mitemVariablesglobales = new javax.swing.JMenuItem();
        mitemCentralizarcodigo = new javax.swing.JMenuItem();
        mitemLayoutss = new javax.swing.JMenuItem();
        mitemlayoutsYpaneles = new javax.swing.JMenuItem();
        mitemDialogos_ = new javax.swing.JMenuItem();
        jmenuSalir = new javax.swing.JMenu();
        mitem_salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU PRINCIPAL");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU PRINCIPAL");

        jLabel2.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Usuario: Administrador");

        jmenuUsuario.setText("Usuario");

        mitemcambiarUsuario.setText("Cambiar de Usuario");
        mitemcambiarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemcambiarUsuarioActionPerformed(evt);
            }
        });
        jmenuUsuario.add(mitemcambiarUsuario);

        barra_menuPrincipal.add(jmenuUsuario);

        jmenuReferenciales.setText("Referenciales");

        mitem_ciudad.setText("Ciudad");
        mitem_ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_ciudadActionPerformed(evt);
            }
        });
        jmenuReferenciales.add(mitem_ciudad);

        mitem_pais.setText("Pais");
        mitem_pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_paisActionPerformed(evt);
            }
        });
        jmenuReferenciales.add(mitem_pais);

        mitem_registrosdatos.setText("Registro de Datos");
        mitem_registrosdatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_registrosdatosActionPerformed(evt);
            }
        });
        jmenuReferenciales.add(mitem_registrosdatos);

        barra_menuPrincipal.add(jmenuReferenciales);

        jmenuCalculadora.setText("Calculadora");
        jmenuCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCalculadoraActionPerformed(evt);
            }
        });

        mitem_calculadora.setText("Calculadora Beta");
        mitem_calculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_calculadoraActionPerformed(evt);
            }
        });
        jmenuCalculadora.add(mitem_calculadora);

        barra_menuPrincipal.add(jmenuCalculadora);

        jmenuMateriales.setText("Materiales");

        jmenuJframeM.setText("JFrame");

        jmenuJframeI.setText("JFrame I");

        mitemcuadrosVerificacion.setText("Cuadro de Verificacion");
        mitemcuadrosVerificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemcuadrosVerificacionActionPerformed(evt);
            }
        });
        jmenuJframeI.add(mitemcuadrosVerificacion);

        mitembotonesOpcion.setText("Botones de Opcion");
        mitembotonesOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitembotonesOpcionActionPerformed(evt);
            }
        });
        jmenuJframeI.add(mitembotonesOpcion);

        mitemlistas.setText("Listas");
        mitemlistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemlistasActionPerformed(evt);
            }
        });
        jmenuJframeI.add(mitemlistas);

        mitemcomboss.setText("Combo");
        mitemcomboss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemcombossActionPerformed(evt);
            }
        });
        jmenuJframeI.add(mitemcomboss);

        mitemlistaModelos.setText("Listas Modelos");
        mitemlistaModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemlistaModelosActionPerformed(evt);
            }
        });
        jmenuJframeI.add(mitemlistaModelos);

        mitemcombosModelos.setText("Combos Modelos");
        mitemcombosModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemcombosModelosActionPerformed(evt);
            }
        });
        jmenuJframeI.add(mitemcombosModelos);

        mitemtoggleButtons.setText("Toggle Buttons");
        mitemtoggleButtons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemtoggleButtonsActionPerformed(evt);
            }
        });
        jmenuJframeI.add(mitemtoggleButtons);

        mitemsliderss.setText("Sliders");
        mitemsliderss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemsliderssActionPerformed(evt);
            }
        });
        jmenuJframeI.add(mitemsliderss);

        mitemSpinners.setText("Spinner");
        mitemSpinners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemSpinnersActionPerformed(evt);
            }
        });
        jmenuJframeI.add(mitemSpinners);

        mitembarraDespl.setText("Barras de Desplazamiento");
        mitembarraDespl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitembarraDesplActionPerformed(evt);
            }
        });
        jmenuJframeI.add(mitembarraDespl);

        jmenuJframeM.add(jmenuJframeI);
        jmenuJframeM.add(jSeparator1);

        jmenuJframeII.setText("JFrame II");

        mitembarraMenus.setText("Barra de Menus");
        mitembarraMenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitembarraMenusActionPerformed(evt);
            }
        });
        jmenuJframeII.add(mitembarraMenus);

        mitembarraHerramientas.setText("Barra de Herramientas");
        mitembarraHerramientas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitembarraHerramientasActionPerformed(evt);
            }
        });
        jmenuJframeII.add(mitembarraHerramientas);

        mitemmenuEmergentes.setText("Menus Emergentes");
        mitemmenuEmergentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemmenuEmergentesActionPerformed(evt);
            }
        });
        jmenuJframeII.add(mitemmenuEmergentes);

        mitemfileChoosers.setText("Filechooser");
        mitemfileChoosers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemfileChoosersActionPerformed(evt);
            }
        });
        jmenuJframeII.add(mitemfileChoosers);

        mitemPanelesdesplazamiento.setText("Paneles de Desplazamiento");
        mitemPanelesdesplazamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemPanelesdesplazamientoActionPerformed(evt);
            }
        });
        jmenuJframeII.add(mitemPanelesdesplazamiento);

        mitemVariablesglobales.setText("Variables Globales");
        mitemVariablesglobales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemVariablesglobalesActionPerformed(evt);
            }
        });
        jmenuJframeII.add(mitemVariablesglobales);

        mitemCentralizarcodigo.setText("Centralizar Codigo");
        mitemCentralizarcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemCentralizarcodigoActionPerformed(evt);
            }
        });
        jmenuJframeII.add(mitemCentralizarcodigo);

        mitemLayoutss.setText("Layouts");
        mitemLayoutss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemLayoutssActionPerformed(evt);
            }
        });
        jmenuJframeII.add(mitemLayoutss);

        mitemlayoutsYpaneles.setText("Layouts y Paneles");
        mitemlayoutsYpaneles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemlayoutsYpanelesActionPerformed(evt);
            }
        });
        jmenuJframeII.add(mitemlayoutsYpaneles);

        mitemDialogos_.setText("Dialogos");
        mitemDialogos_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemDialogos_ActionPerformed(evt);
            }
        });
        jmenuJframeII.add(mitemDialogos_);

        jmenuJframeM.add(jmenuJframeII);

        jmenuMateriales.add(jmenuJframeM);

        barra_menuPrincipal.add(jmenuMateriales);

        jmenuSalir.setText("Salir");
        jmenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuSalirActionPerformed(evt);
            }
        });

        mitem_salir.setText("Salir del Sistema");
        mitem_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_salirActionPerformed(evt);
            }
        });
        jmenuSalir.add(mitem_salir);

        barra_menuPrincipal.add(jmenuSalir);

        setJMenuBar(barra_menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 355, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(46, 46, 46))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mitemcombosModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemcombosModelosActionPerformed
        abrirarchivo("guiados/06_GUIADOS_COMBOS_MODELOS.pdf");
    }//GEN-LAST:event_mitemcombosModelosActionPerformed

    private void mitemcuadrosVerificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemcuadrosVerificacionActionPerformed
        abrirarchivo("guiados/01_GUIADOS_CUADROS_VERIFICACION.pdf");
    }//GEN-LAST:event_mitemcuadrosVerificacionActionPerformed

    private void mitembotonesOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitembotonesOpcionActionPerformed
        abrirarchivo("guiados/02_GUIADOS_BOTONES_DE_OPCION.pdf");
    }//GEN-LAST:event_mitembotonesOpcionActionPerformed

    private void mitemlistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemlistasActionPerformed
        abrirarchivo("guiados/03_GUIADOS_LISTAS.pdf");
    }//GEN-LAST:event_mitemlistasActionPerformed

    private void mitemcombossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemcombossActionPerformed
        abrirarchivo("guiados/04_GUIADOS_COMBO.pdf");
                
    }//GEN-LAST:event_mitemcombossActionPerformed

    private void mitemlistaModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemlistaModelosActionPerformed
        abrirarchivo("guiados/05_GUIADOS_LISTAS_MODELOS.pdf");
    }//GEN-LAST:event_mitemlistaModelosActionPerformed

    private void mitemtoggleButtonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemtoggleButtonsActionPerformed
        abrirarchivo("guiados/07_GUIADOS_TOGGLEBUTTONS.pdf");
    }//GEN-LAST:event_mitemtoggleButtonsActionPerformed

    private void mitemsliderssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemsliderssActionPerformed
        abrirarchivo("guiados/08_GUIADOS_SLIDERS.pdf");
    }//GEN-LAST:event_mitemsliderssActionPerformed

    private void mitemSpinnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemSpinnersActionPerformed
        abrirarchivo("guiados/09_GUIADOS_SPINNER.pdf");
    }//GEN-LAST:event_mitemSpinnersActionPerformed

    private void mitembarraDesplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitembarraDesplActionPerformed
        abrirarchivo("guiados/10_GUIADOS_BARRAS_DESPLAZAMIENTO.pdf");
    }//GEN-LAST:event_mitembarraDesplActionPerformed

    private void mitembarraMenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitembarraMenusActionPerformed
        abrirarchivo("guiados/11_GUIADO_BARRA_DE_MENUS.pdf");
    }//GEN-LAST:event_mitembarraMenusActionPerformed

    private void mitembarraHerramientasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitembarraHerramientasActionPerformed
        abrirarchivo("guiados/12_GUIADO_BARRA_DE_HERRAMIENTAS.pdf");
    }//GEN-LAST:event_mitembarraHerramientasActionPerformed

    private void mitemmenuEmergentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemmenuEmergentesActionPerformed
        abrirarchivo("guiados/13_GUIADO_MENUS_EMERGENTES.pdf");
    }//GEN-LAST:event_mitemmenuEmergentesActionPerformed

    private void mitemfileChoosersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemfileChoosersActionPerformed
        abrirarchivo("guiados/14_GUIADO_FILECHOOSER.pdf");
    }//GEN-LAST:event_mitemfileChoosersActionPerformed

    private void mitemPanelesdesplazamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemPanelesdesplazamientoActionPerformed
        abrirarchivo("guiados/15_GUIADO_PANELES DE DESPLAZAMIENTO.pdf");
    }//GEN-LAST:event_mitemPanelesdesplazamientoActionPerformed

    private void mitemVariablesglobalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemVariablesglobalesActionPerformed
        abrirarchivo("guiados/16_GUIADO_VARIABLES_GLOBALES.pdf");
    }//GEN-LAST:event_mitemVariablesglobalesActionPerformed

    private void mitemCentralizarcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemCentralizarcodigoActionPerformed
        abrirarchivo("guiados/17_GUIADO_CENTRALIZAR CÓDIGO.pdf");
    }//GEN-LAST:event_mitemCentralizarcodigoActionPerformed

    private void mitemLayoutssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemLayoutssActionPerformed
        abrirarchivo("guiados/18_GUIADO_LAYOUTS.pdf");
    }//GEN-LAST:event_mitemLayoutssActionPerformed

    private void mitemlayoutsYpanelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemlayoutsYpanelesActionPerformed
        abrirarchivo("guiados/19_GUIADO_LAYOUTS Y PANELES.pdf");
    }//GEN-LAST:event_mitemlayoutsYpanelesActionPerformed

    private void mitemDialogos_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemDialogos_ActionPerformed
        abrirarchivo("guiados/20_GUIADO_DIÁLOGOS.pdf");
    }//GEN-LAST:event_mitemDialogos_ActionPerformed

    private void mitemcambiarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemcambiarUsuarioActionPerformed
        new Login().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitemcambiarUsuarioActionPerformed

    private void jmenuCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCalculadoraActionPerformed
        
    }//GEN-LAST:event_jmenuCalculadoraActionPerformed

    private void jmenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuSalirActionPerformed
        
    }//GEN-LAST:event_jmenuSalirActionPerformed

    private void mitem_ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_ciudadActionPerformed
        new ciudades().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem_ciudadActionPerformed

    private void mitem_paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_paisActionPerformed
        new paises().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem_paisActionPerformed

    private void mitem_registrosdatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_registrosdatosActionPerformed
        new registro_de_datos().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem_registrosdatosActionPerformed

    private void mitem_calculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_calculadoraActionPerformed
        new calculadora().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem_calculadoraActionPerformed

    private void mitem_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_salirActionPerformed
        int selec = JOptionPane.showConfirmDialog(null,"Desea Salir?","SALIR",JOptionPane.DEFAULT_OPTION,JOptionPane.YES_NO_OPTION);
        if(selec == 0){
            dispose();
        }
    }//GEN-LAST:event_mitem_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barra_menuPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu jmenuCalculadora;
    private javax.swing.JMenu jmenuJframeI;
    private javax.swing.JMenu jmenuJframeII;
    private javax.swing.JMenu jmenuJframeM;
    private javax.swing.JMenu jmenuMateriales;
    private javax.swing.JMenu jmenuReferenciales;
    private javax.swing.JMenu jmenuSalir;
    private javax.swing.JMenu jmenuUsuario;
    private javax.swing.JMenuItem mitemCentralizarcodigo;
    private javax.swing.JMenuItem mitemDialogos_;
    private javax.swing.JMenuItem mitemLayoutss;
    private javax.swing.JMenuItem mitemPanelesdesplazamiento;
    private javax.swing.JMenuItem mitemSpinners;
    private javax.swing.JMenuItem mitemVariablesglobales;
    private javax.swing.JMenuItem mitem_calculadora;
    private javax.swing.JMenuItem mitem_ciudad;
    private javax.swing.JMenuItem mitem_pais;
    private javax.swing.JMenuItem mitem_registrosdatos;
    private javax.swing.JMenuItem mitem_salir;
    private javax.swing.JMenuItem mitembarraDespl;
    private javax.swing.JMenuItem mitembarraHerramientas;
    private javax.swing.JMenuItem mitembarraMenus;
    private javax.swing.JMenuItem mitembotonesOpcion;
    private javax.swing.JMenuItem mitemcambiarUsuario;
    private javax.swing.JMenuItem mitemcombosModelos;
    private javax.swing.JMenuItem mitemcomboss;
    private javax.swing.JMenuItem mitemcuadrosVerificacion;
    private javax.swing.JMenuItem mitemfileChoosers;
    private javax.swing.JMenuItem mitemlayoutsYpaneles;
    private javax.swing.JMenuItem mitemlistaModelos;
    private javax.swing.JMenuItem mitemlistas;
    private javax.swing.JMenuItem mitemmenuEmergentes;
    private javax.swing.JMenuItem mitemsliderss;
    private javax.swing.JMenuItem mitemtoggleButtons;
    // End of variables declaration//GEN-END:variables
}
