/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;
import JFrame.*;
import Login.Login;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class menu_secundario extends javax.swing.JFrame {

    /**
     * Creates new form menu_secundario
     */
    public menu_secundario() {
        initComponents();
        //icono de ventana
        setIconImage(new ImageIcon(getClass().getResource("../imagenes/login.jpg")).getImage());
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    //Metodo para abrir los archivos pdf
    public void abrirarchivo(String archivo){
        try{
            File path = new File(archivo);
            Desktop.getDesktop().open(path);
        }catch (IOException ex){
            System.out.println(ex);
        }
    }
    //Metodo para ejecutar archivos .exe
   public void ejecutar(String cmd){
        try {
            Runtime correr = Runtime.getRuntime();
            
            Process process = correr.exec(cmd);
            
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        barramenusecundario = new javax.swing.JMenuBar();
        jmenuUsuario = new javax.swing.JMenu();
        mitemcambiarUsuario = new javax.swing.JMenuItem();
        jmenuJFrame = new javax.swing.JMenu();
        mitem_1cuadrosverificacion = new javax.swing.JMenuItem();
        mitem_2botonesdeopcion = new javax.swing.JMenuItem();
        mitem_3listas = new javax.swing.JMenuItem();
        mitem_4combos = new javax.swing.JMenuItem();
        mitem_5listasmodelos = new javax.swing.JMenuItem();
        mitem_6combosmodelos = new javax.swing.JMenuItem();
        mitem_7togglebutons = new javax.swing.JMenuItem();
        mitem_8sliders = new javax.swing.JMenuItem();
        mitem_9spinner = new javax.swing.JMenuItem();
        mitem_10barrasdespla = new javax.swing.JMenuItem();
        separador = new javax.swing.JPopupMenu.Separator();
        mitem_11barramenu = new javax.swing.JMenuItem();
        mitem_12barraherramientas = new javax.swing.JMenuItem();
        mitem_13menuemergente = new javax.swing.JMenuItem();
        mitem_14filechooser = new javax.swing.JMenuItem();
        mitem_15panelesdesplaz = new javax.swing.JMenuItem();
        mitem_16variablesglobales = new javax.swing.JMenuItem();
        mitem_17centralizarcodigo = new javax.swing.JMenuItem();
        mitem18_layouts = new javax.swing.JMenuItem();
        mitem_19layoutsypaneles = new javax.swing.JMenuItem();
        mitem_20dialogos = new javax.swing.JMenuItem();
        jmenuConsola = new javax.swing.JMenu();
        jmenu1pdf = new javax.swing.JMenu();
        mitem_consola1 = new javax.swing.JMenuItem();
        mitem_consola2 = new javax.swing.JMenuItem();
        mitem_consola3 = new javax.swing.JMenuItem();
        mitem_consola4 = new javax.swing.JMenuItem();
        mitem_consola5 = new javax.swing.JMenuItem();
        mitem_consola6 = new javax.swing.JMenuItem();
        mitem_consola7 = new javax.swing.JMenuItem();
        mitem_consola8 = new javax.swing.JMenuItem();
        mitem_consola9 = new javax.swing.JMenuItem();
        mitem_consola10 = new javax.swing.JMenuItem();
        jmenu2pdf = new javax.swing.JMenu();
        mitem_consola21 = new javax.swing.JMenuItem();
        mitem_consola22 = new javax.swing.JMenuItem();
        mitem_consola23 = new javax.swing.JMenuItem();
        mitem_consola24 = new javax.swing.JMenuItem();
        mitem_consola25 = new javax.swing.JMenuItem();
        mitem_consola26 = new javax.swing.JMenuItem();
        mitem_consola27 = new javax.swing.JMenuItem();
        mitem_consola28 = new javax.swing.JMenuItem();
        mitem_consola29 = new javax.swing.JMenuItem();
        mitem_consola210 = new javax.swing.JMenuItem();
        jmenu3pdf = new javax.swing.JMenu();
        mitem_consola31 = new javax.swing.JMenuItem();
        mitem_consola32 = new javax.swing.JMenuItem();
        mitem_consola33 = new javax.swing.JMenuItem();
        mitem_consola34 = new javax.swing.JMenuItem();
        mitem_consola35 = new javax.swing.JMenuItem();
        mitem_consola36 = new javax.swing.JMenuItem();
        mitem_consola37 = new javax.swing.JMenuItem();
        mitem_consola38 = new javax.swing.JMenuItem();
        mitem_consola39 = new javax.swing.JMenuItem();
        mitem_consola310 = new javax.swing.JMenuItem();
        jmenu4pdf = new javax.swing.JMenu();
        mitem_consola41 = new javax.swing.JMenuItem();
        mitem_consola42 = new javax.swing.JMenuItem();
        mitem_consola43 = new javax.swing.JMenuItem();
        mitem_consola44 = new javax.swing.JMenuItem();
        mitem_consola45 = new javax.swing.JMenuItem();
        mitem_consola46 = new javax.swing.JMenuItem();
        mitem_consola47 = new javax.swing.JMenuItem();
        miem_consola48 = new javax.swing.JMenuItem();
        mitem_consola49 = new javax.swing.JMenuItem();
        jmenuMateriales = new javax.swing.JMenu();
        jmenuJframepdf = new javax.swing.JMenu();
        jmenuJframeIpdf = new javax.swing.JMenu();
        mitem_jf_1pdf = new javax.swing.JMenuItem();
        mitem_jf_2pdf = new javax.swing.JMenuItem();
        mitem_jf_3pdf = new javax.swing.JMenuItem();
        mitem_jf_4pdf = new javax.swing.JMenuItem();
        mitem_jf_5pdf = new javax.swing.JMenuItem();
        mitem_jf_6pdf = new javax.swing.JMenuItem();
        mitem_jf_7pdf = new javax.swing.JMenuItem();
        mitem_jf_8pdf = new javax.swing.JMenuItem();
        mitem_jf_9pdf = new javax.swing.JMenuItem();
        mitem_jf_10pdf = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmenuJframeIIpdf = new javax.swing.JMenu();
        mitem_jf_11pdf = new javax.swing.JMenuItem();
        mitem_jf_12pdf = new javax.swing.JMenuItem();
        mitem_jf_13pdf = new javax.swing.JMenuItem();
        mitem_jf_14pdf = new javax.swing.JMenuItem();
        mitem_jf_15pdf = new javax.swing.JMenuItem();
        mitem_jf_16pdf = new javax.swing.JMenuItem();
        mitem_jf_17pdf = new javax.swing.JMenuItem();
        mitem_jf_18pdf = new javax.swing.JMenuItem();
        mitem_jf_19pdf = new javax.swing.JMenuItem();
        mitem_jf_20pdf = new javax.swing.JMenuItem();
        jmenuSalir = new javax.swing.JMenu();
        mitem_salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU SECUNDARIO");

        jLabel2.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Usuario: Admin");

        jmenuUsuario.setText("Usuario");

        mitemcambiarUsuario.setText("Cambiar de Usuario");
        mitemcambiarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemcambiarUsuarioActionPerformed(evt);
            }
        });
        jmenuUsuario.add(mitemcambiarUsuario);

        barramenusecundario.add(jmenuUsuario);

        jmenuJFrame.setText("JFrame");

        mitem_1cuadrosverificacion.setText("Cuadro de Verificacion");
        mitem_1cuadrosverificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_1cuadrosverificacionActionPerformed(evt);
            }
        });
        jmenuJFrame.add(mitem_1cuadrosverificacion);

        mitem_2botonesdeopcion.setText("Botones de Opcion");
        mitem_2botonesdeopcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_2botonesdeopcionActionPerformed(evt);
            }
        });
        jmenuJFrame.add(mitem_2botonesdeopcion);

        mitem_3listas.setText("Listas");
        mitem_3listas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_3listasActionPerformed(evt);
            }
        });
        jmenuJFrame.add(mitem_3listas);

        mitem_4combos.setText("Combo");
        mitem_4combos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_4combosActionPerformed(evt);
            }
        });
        jmenuJFrame.add(mitem_4combos);

        mitem_5listasmodelos.setText("Listas Modelos");
        mitem_5listasmodelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_5listasmodelosActionPerformed(evt);
            }
        });
        jmenuJFrame.add(mitem_5listasmodelos);

        mitem_6combosmodelos.setText("Combos Modelos");
        mitem_6combosmodelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_6combosmodelosActionPerformed(evt);
            }
        });
        jmenuJFrame.add(mitem_6combosmodelos);

        mitem_7togglebutons.setText("ToggleButtons");
        mitem_7togglebutons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_7togglebutonsActionPerformed(evt);
            }
        });
        jmenuJFrame.add(mitem_7togglebutons);

        mitem_8sliders.setText("Sliders");
        mitem_8sliders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_8slidersActionPerformed(evt);
            }
        });
        jmenuJFrame.add(mitem_8sliders);

        mitem_9spinner.setText("Spinner");
        mitem_9spinner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_9spinnerActionPerformed(evt);
            }
        });
        jmenuJFrame.add(mitem_9spinner);

        mitem_10barrasdespla.setText("Barra de Desplazamiento");
        mitem_10barrasdespla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_10barrasdesplaActionPerformed(evt);
            }
        });
        jmenuJFrame.add(mitem_10barrasdespla);
        jmenuJFrame.add(separador);

        mitem_11barramenu.setText("Barra de Menus");
        mitem_11barramenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_11barramenuActionPerformed(evt);
            }
        });
        jmenuJFrame.add(mitem_11barramenu);

        mitem_12barraherramientas.setText("Barra de Herramientas");
        mitem_12barraherramientas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_12barraherramientasActionPerformed(evt);
            }
        });
        jmenuJFrame.add(mitem_12barraherramientas);

        mitem_13menuemergente.setText("Menus Emergentes");
        mitem_13menuemergente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_13menuemergenteActionPerformed(evt);
            }
        });
        jmenuJFrame.add(mitem_13menuemergente);

        mitem_14filechooser.setText("FileChooser");
        mitem_14filechooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_14filechooserActionPerformed(evt);
            }
        });
        jmenuJFrame.add(mitem_14filechooser);

        mitem_15panelesdesplaz.setText("Paneles de Desplazamiento");
        mitem_15panelesdesplaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_15panelesdesplazActionPerformed(evt);
            }
        });
        jmenuJFrame.add(mitem_15panelesdesplaz);

        mitem_16variablesglobales.setText("Variables Globales");
        mitem_16variablesglobales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_16variablesglobalesActionPerformed(evt);
            }
        });
        jmenuJFrame.add(mitem_16variablesglobales);

        mitem_17centralizarcodigo.setText("Centralizar Codigo");
        mitem_17centralizarcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_17centralizarcodigoActionPerformed(evt);
            }
        });
        jmenuJFrame.add(mitem_17centralizarcodigo);

        mitem18_layouts.setText("Layouts");
        mitem18_layouts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem18_layoutsActionPerformed(evt);
            }
        });
        jmenuJFrame.add(mitem18_layouts);

        mitem_19layoutsypaneles.setText("Layouts y Paneles");
        mitem_19layoutsypaneles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_19layoutsypanelesActionPerformed(evt);
            }
        });
        jmenuJFrame.add(mitem_19layoutsypaneles);

        mitem_20dialogos.setText("Dialogos");
        mitem_20dialogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_20dialogosActionPerformed(evt);
            }
        });
        jmenuJFrame.add(mitem_20dialogos);

        barramenusecundario.add(jmenuJFrame);

        jmenuConsola.setText("Consola");

        jmenu1pdf.setText("Ejercicio 1");

        mitem_consola1.setText("Ejercicio 1.1");
        mitem_consola1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola1ActionPerformed(evt);
            }
        });
        jmenu1pdf.add(mitem_consola1);

        mitem_consola2.setText("Ejercicio 1.2");
        mitem_consola2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola2ActionPerformed(evt);
            }
        });
        jmenu1pdf.add(mitem_consola2);

        mitem_consola3.setText("Ejercicio 1.3");
        mitem_consola3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola3ActionPerformed(evt);
            }
        });
        jmenu1pdf.add(mitem_consola3);

        mitem_consola4.setText("Ejercicio 1.4");
        mitem_consola4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola4ActionPerformed(evt);
            }
        });
        jmenu1pdf.add(mitem_consola4);

        mitem_consola5.setText("Ejercicio 1.5");
        mitem_consola5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola5ActionPerformed(evt);
            }
        });
        jmenu1pdf.add(mitem_consola5);

        mitem_consola6.setText("Ejercicio 1.6");
        mitem_consola6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola6ActionPerformed(evt);
            }
        });
        jmenu1pdf.add(mitem_consola6);

        mitem_consola7.setText("Ejercicio 1.7");
        mitem_consola7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola7ActionPerformed(evt);
            }
        });
        jmenu1pdf.add(mitem_consola7);

        mitem_consola8.setText("Ejercicio 1.8");
        mitem_consola8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola8ActionPerformed(evt);
            }
        });
        jmenu1pdf.add(mitem_consola8);

        mitem_consola9.setText("Ejercicio 1.9");
        mitem_consola9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola9ActionPerformed(evt);
            }
        });
        jmenu1pdf.add(mitem_consola9);

        mitem_consola10.setText("Ejercicio 1.10");
        mitem_consola10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola10ActionPerformed(evt);
            }
        });
        jmenu1pdf.add(mitem_consola10);

        jmenuConsola.add(jmenu1pdf);

        jmenu2pdf.setText("Ejercicio 2");

        mitem_consola21.setText("Ejercicio 2.1");
        mitem_consola21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola21ActionPerformed(evt);
            }
        });
        jmenu2pdf.add(mitem_consola21);

        mitem_consola22.setText("Ejercicio 2.2");
        mitem_consola22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola22ActionPerformed(evt);
            }
        });
        jmenu2pdf.add(mitem_consola22);

        mitem_consola23.setText("Ejercicio 2.3");
        mitem_consola23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola23ActionPerformed(evt);
            }
        });
        jmenu2pdf.add(mitem_consola23);

        mitem_consola24.setText("Ejercicio 2.4");
        mitem_consola24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola24ActionPerformed(evt);
            }
        });
        jmenu2pdf.add(mitem_consola24);

        mitem_consola25.setText("Ejercicio 2.5");
        mitem_consola25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola25ActionPerformed(evt);
            }
        });
        jmenu2pdf.add(mitem_consola25);

        mitem_consola26.setText("Ejercicio 2.6");
        mitem_consola26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola26ActionPerformed(evt);
            }
        });
        jmenu2pdf.add(mitem_consola26);

        mitem_consola27.setText("Ejercicio 2.7");
        mitem_consola27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola27ActionPerformed(evt);
            }
        });
        jmenu2pdf.add(mitem_consola27);

        mitem_consola28.setText("Ejercicio 2.8");
        mitem_consola28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola28ActionPerformed(evt);
            }
        });
        jmenu2pdf.add(mitem_consola28);

        mitem_consola29.setText("Ejercicio 2.9");
        mitem_consola29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola29ActionPerformed(evt);
            }
        });
        jmenu2pdf.add(mitem_consola29);

        mitem_consola210.setText("Ejercicio 2.10");
        mitem_consola210.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola210ActionPerformed(evt);
            }
        });
        jmenu2pdf.add(mitem_consola210);

        jmenuConsola.add(jmenu2pdf);

        jmenu3pdf.setText("Ejercicio 3");

        mitem_consola31.setText("Ejercicio 3.1");
        mitem_consola31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola31ActionPerformed(evt);
            }
        });
        jmenu3pdf.add(mitem_consola31);

        mitem_consola32.setText("Ejercicio 3.2");
        mitem_consola32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola32ActionPerformed(evt);
            }
        });
        jmenu3pdf.add(mitem_consola32);

        mitem_consola33.setText("Ejercicio 3.3");
        mitem_consola33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola33ActionPerformed(evt);
            }
        });
        jmenu3pdf.add(mitem_consola33);

        mitem_consola34.setText("Ejercicio 3.4");
        mitem_consola34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola34ActionPerformed(evt);
            }
        });
        jmenu3pdf.add(mitem_consola34);

        mitem_consola35.setText("Ejercicio 3.5");
        mitem_consola35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola35ActionPerformed(evt);
            }
        });
        jmenu3pdf.add(mitem_consola35);

        mitem_consola36.setText("Ejercicio 3.6");
        mitem_consola36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola36ActionPerformed(evt);
            }
        });
        jmenu3pdf.add(mitem_consola36);

        mitem_consola37.setText("Ejercicio 3.7");
        mitem_consola37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola37ActionPerformed(evt);
            }
        });
        jmenu3pdf.add(mitem_consola37);

        mitem_consola38.setText("Ejercicio 3.8");
        mitem_consola38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola38ActionPerformed(evt);
            }
        });
        jmenu3pdf.add(mitem_consola38);

        mitem_consola39.setText("Ejercicio 3.9");
        mitem_consola39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola39ActionPerformed(evt);
            }
        });
        jmenu3pdf.add(mitem_consola39);

        mitem_consola310.setText("Ejercicio 3.10");
        mitem_consola310.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola310ActionPerformed(evt);
            }
        });
        jmenu3pdf.add(mitem_consola310);

        jmenuConsola.add(jmenu3pdf);

        jmenu4pdf.setText("Ejercicio 4");

        mitem_consola41.setText("Ejercicio 4.1");
        mitem_consola41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola41ActionPerformed(evt);
            }
        });
        jmenu4pdf.add(mitem_consola41);

        mitem_consola42.setText("Ejercicio 4.2");
        mitem_consola42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola42ActionPerformed(evt);
            }
        });
        jmenu4pdf.add(mitem_consola42);

        mitem_consola43.setText("Ejercicio 4.3");
        mitem_consola43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola43ActionPerformed(evt);
            }
        });
        jmenu4pdf.add(mitem_consola43);

        mitem_consola44.setText("Ejercicio 4.4");
        mitem_consola44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola44ActionPerformed(evt);
            }
        });
        jmenu4pdf.add(mitem_consola44);

        mitem_consola45.setText("Ejercicio 4.5");
        mitem_consola45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola45ActionPerformed(evt);
            }
        });
        jmenu4pdf.add(mitem_consola45);

        mitem_consola46.setText("Ejercicio 4.6");
        mitem_consola46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola46ActionPerformed(evt);
            }
        });
        jmenu4pdf.add(mitem_consola46);

        mitem_consola47.setText("Ejercicio 4.7");
        mitem_consola47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola47ActionPerformed(evt);
            }
        });
        jmenu4pdf.add(mitem_consola47);

        miem_consola48.setText("Ejercicio 4.8");
        miem_consola48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miem_consola48ActionPerformed(evt);
            }
        });
        jmenu4pdf.add(miem_consola48);

        mitem_consola49.setText("Ejercicio 4.9");
        mitem_consola49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_consola49ActionPerformed(evt);
            }
        });
        jmenu4pdf.add(mitem_consola49);

        jmenuConsola.add(jmenu4pdf);

        barramenusecundario.add(jmenuConsola);

        jmenuMateriales.setText("Materiales");

        jmenuJframepdf.setText("JFrame");

        jmenuJframeIpdf.setText("JFame I");

        mitem_jf_1pdf.setText("Cuadros de Verificacion");
        mitem_jf_1pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_jf_1pdfActionPerformed(evt);
            }
        });
        jmenuJframeIpdf.add(mitem_jf_1pdf);

        mitem_jf_2pdf.setText("Botones de Opcion");
        mitem_jf_2pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_jf_2pdfActionPerformed(evt);
            }
        });
        jmenuJframeIpdf.add(mitem_jf_2pdf);

        mitem_jf_3pdf.setText("Listas");
        mitem_jf_3pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_jf_3pdfActionPerformed(evt);
            }
        });
        jmenuJframeIpdf.add(mitem_jf_3pdf);

        mitem_jf_4pdf.setText("Combo");
        mitem_jf_4pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_jf_4pdfActionPerformed(evt);
            }
        });
        jmenuJframeIpdf.add(mitem_jf_4pdf);

        mitem_jf_5pdf.setText("Listas Modelos");
        mitem_jf_5pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_jf_5pdfActionPerformed(evt);
            }
        });
        jmenuJframeIpdf.add(mitem_jf_5pdf);

        mitem_jf_6pdf.setText("Combo Modelos");
        mitem_jf_6pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_jf_6pdfActionPerformed(evt);
            }
        });
        jmenuJframeIpdf.add(mitem_jf_6pdf);

        mitem_jf_7pdf.setText("ToggleButtons");
        mitem_jf_7pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_jf_7pdfActionPerformed(evt);
            }
        });
        jmenuJframeIpdf.add(mitem_jf_7pdf);

        mitem_jf_8pdf.setText("Sliders");
        mitem_jf_8pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_jf_8pdfActionPerformed(evt);
            }
        });
        jmenuJframeIpdf.add(mitem_jf_8pdf);

        mitem_jf_9pdf.setText("Spinner");
        mitem_jf_9pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_jf_9pdfActionPerformed(evt);
            }
        });
        jmenuJframeIpdf.add(mitem_jf_9pdf);

        mitem_jf_10pdf.setText("Barra de Desplazamiento");
        mitem_jf_10pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_jf_10pdfActionPerformed(evt);
            }
        });
        jmenuJframeIpdf.add(mitem_jf_10pdf);

        jmenuJframepdf.add(jmenuJframeIpdf);
        jmenuJframepdf.add(jSeparator1);

        jmenuJframeIIpdf.setText("JFrame II");

        mitem_jf_11pdf.setText("Barra de Menus");
        mitem_jf_11pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_jf_11pdfActionPerformed(evt);
            }
        });
        jmenuJframeIIpdf.add(mitem_jf_11pdf);

        mitem_jf_12pdf.setText("Barra de Herramientas");
        mitem_jf_12pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_jf_12pdfActionPerformed(evt);
            }
        });
        jmenuJframeIIpdf.add(mitem_jf_12pdf);

        mitem_jf_13pdf.setText("Menus Emergentes");
        mitem_jf_13pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_jf_13pdfActionPerformed(evt);
            }
        });
        jmenuJframeIIpdf.add(mitem_jf_13pdf);

        mitem_jf_14pdf.setText("FileChooser");
        mitem_jf_14pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_jf_14pdfActionPerformed(evt);
            }
        });
        jmenuJframeIIpdf.add(mitem_jf_14pdf);

        mitem_jf_15pdf.setText("Paneles de Desplazamiento");
        mitem_jf_15pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_jf_15pdfActionPerformed(evt);
            }
        });
        jmenuJframeIIpdf.add(mitem_jf_15pdf);

        mitem_jf_16pdf.setText("Variables Globales");
        mitem_jf_16pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_jf_16pdfActionPerformed(evt);
            }
        });
        jmenuJframeIIpdf.add(mitem_jf_16pdf);

        mitem_jf_17pdf.setText("Centralizar Codigo");
        mitem_jf_17pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_jf_17pdfActionPerformed(evt);
            }
        });
        jmenuJframeIIpdf.add(mitem_jf_17pdf);

        mitem_jf_18pdf.setText("Layouts");
        mitem_jf_18pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_jf_18pdfActionPerformed(evt);
            }
        });
        jmenuJframeIIpdf.add(mitem_jf_18pdf);

        mitem_jf_19pdf.setText("Layouts y Paneles");
        mitem_jf_19pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_jf_19pdfActionPerformed(evt);
            }
        });
        jmenuJframeIIpdf.add(mitem_jf_19pdf);

        mitem_jf_20pdf.setText("Dialogos");
        mitem_jf_20pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_jf_20pdfActionPerformed(evt);
            }
        });
        jmenuJframeIIpdf.add(mitem_jf_20pdf);

        jmenuJframepdf.add(jmenuJframeIIpdf);

        jmenuMateriales.add(jmenuJframepdf);

        barramenusecundario.add(jmenuMateriales);

        jmenuSalir.setText("Salir");

        mitem_salir.setText("Salir del Sistema");
        mitem_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_salirActionPerformed(evt);
            }
        });
        jmenuSalir.add(mitem_salir);

        barramenusecundario.add(jmenuSalir);

        setJMenuBar(barramenusecundario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(50, 50, 50))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mitem_3listasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_3listasActionPerformed
        new lista().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem_3listasActionPerformed

    private void mitem_1cuadrosverificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_1cuadrosverificacionActionPerformed
        new Cuadro_listas().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem_1cuadrosverificacionActionPerformed

    private void mitem_jf_1pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_jf_1pdfActionPerformed
        abrirarchivo("guiados/01_GUIADOS_CUADROS_VERIFICACION.pdf");
    }//GEN-LAST:event_mitem_jf_1pdfActionPerformed

    private void mitem_jf_2pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_jf_2pdfActionPerformed
        
        abrirarchivo("guiados/02_GUIADOS_BOTONES_DE_OPCION.pdf");
    }//GEN-LAST:event_mitem_jf_2pdfActionPerformed

    private void mitem_jf_3pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_jf_3pdfActionPerformed
        abrirarchivo("guiados/03_GUIADOS_LISTAS.pdf");
    }//GEN-LAST:event_mitem_jf_3pdfActionPerformed

    private void mitem_jf_4pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_jf_4pdfActionPerformed
        abrirarchivo("guiados/04_GUIADOS_COMBO.pdf");
    }//GEN-LAST:event_mitem_jf_4pdfActionPerformed

    private void mitem_jf_5pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_jf_5pdfActionPerformed
        abrirarchivo("guiados/05_GUIADOS_LISTAS_MODELOS.pdf");
    }//GEN-LAST:event_mitem_jf_5pdfActionPerformed

    private void mitem_jf_6pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_jf_6pdfActionPerformed
        abrirarchivo("guiados/06_GUIADOS_COMBOS_MODELOS.pdf");
    }//GEN-LAST:event_mitem_jf_6pdfActionPerformed

    private void mitem_jf_7pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_jf_7pdfActionPerformed
        abrirarchivo("guiados/07_GUIADOS_TOGGLEBUTTONS.pdf");
    }//GEN-LAST:event_mitem_jf_7pdfActionPerformed

    private void mitem_jf_8pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_jf_8pdfActionPerformed
        abrirarchivo("guiados/08_GUIADOS_SLIDERS.pdf");
    }//GEN-LAST:event_mitem_jf_8pdfActionPerformed

    private void mitem_jf_9pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_jf_9pdfActionPerformed
        abrirarchivo("guiados/09_GUIADOS_SPINNER.pdf");
    }//GEN-LAST:event_mitem_jf_9pdfActionPerformed

    private void mitem_jf_10pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_jf_10pdfActionPerformed
        abrirarchivo("guiados/10_GUIADOS_BARRAS_DESPLAZAMIENTO.pdf");
    }//GEN-LAST:event_mitem_jf_10pdfActionPerformed

    private void mitem_jf_11pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_jf_11pdfActionPerformed
        abrirarchivo("guiados/11_GUIADO_BARRA_DE_MENUS.pdf");
    }//GEN-LAST:event_mitem_jf_11pdfActionPerformed

    private void mitem_jf_12pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_jf_12pdfActionPerformed
        abrirarchivo("guiados/12_GUIADO_BARRA_DE_HERRAMIENTAS.pdf");
    }//GEN-LAST:event_mitem_jf_12pdfActionPerformed

    private void mitem_jf_13pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_jf_13pdfActionPerformed
        abrirarchivo("guiados/13_GUIADO_MENUS_EMERGENTES.pdf");
    }//GEN-LAST:event_mitem_jf_13pdfActionPerformed

    private void mitem_jf_14pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_jf_14pdfActionPerformed
        abrirarchivo("guiados/14_GUIADO_FILECHOOSER.pdf");
    }//GEN-LAST:event_mitem_jf_14pdfActionPerformed

    private void mitem_jf_15pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_jf_15pdfActionPerformed
        abrirarchivo("guiados/15_GUIADO_PANELES DE DESPLAZAMIENTO.pdf");
    }//GEN-LAST:event_mitem_jf_15pdfActionPerformed

    private void mitem_jf_16pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_jf_16pdfActionPerformed
        abrirarchivo("guiados/16_GUIADO_VARIABLES_GLOBALES.pdf");
    }//GEN-LAST:event_mitem_jf_16pdfActionPerformed

    private void mitem_jf_17pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_jf_17pdfActionPerformed
        abrirarchivo("guiados/17_GUIADO_CENTRALIZAR CÓDIGO.pdf");
    }//GEN-LAST:event_mitem_jf_17pdfActionPerformed

    private void mitem_jf_18pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_jf_18pdfActionPerformed
        abrirarchivo("guiados/18_GUIADO_LAYOUTS.pdf");
    }//GEN-LAST:event_mitem_jf_18pdfActionPerformed

    private void mitem_jf_19pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_jf_19pdfActionPerformed
        abrirarchivo("guiados/19_GUIADO_LAYOUTS Y PANELES.pdf");
    }//GEN-LAST:event_mitem_jf_19pdfActionPerformed

    private void mitem_jf_20pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_jf_20pdfActionPerformed
        abrirarchivo("guiados/20_GUIADO_DIÁLOGOS.pdf");
    }//GEN-LAST:event_mitem_jf_20pdfActionPerformed

    private void mitem_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_salirActionPerformed
        int seleccion = JOptionPane.showConfirmDialog(null, "Desea Salir?", "Salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(seleccion == 0){
            dispose();
        }
    }//GEN-LAST:event_mitem_salirActionPerformed

    private void mitem_consola1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola1ActionPerformed
        ejecutar("consola/consola1.exe");
    }//GEN-LAST:event_mitem_consola1ActionPerformed

    private void mitem_consola2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola2ActionPerformed
        ejecutar("consola/consola2.exe");
    }//GEN-LAST:event_mitem_consola2ActionPerformed

    private void mitem_consola3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola3ActionPerformed
        ejecutar("consola/consola3.exe");
    }//GEN-LAST:event_mitem_consola3ActionPerformed

    private void mitem_consola4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola4ActionPerformed
        ejecutar("consola/consola4.exe");
    }//GEN-LAST:event_mitem_consola4ActionPerformed

    private void mitem_consola5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola5ActionPerformed
        ejecutar("consola/consola5.exe");
    }//GEN-LAST:event_mitem_consola5ActionPerformed

    private void mitem_consola6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola6ActionPerformed
        ejecutar("consola/consola6.exe");
    }//GEN-LAST:event_mitem_consola6ActionPerformed

    private void mitem_consola7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola7ActionPerformed
        ejecutar("consola/consola7.exe");
    }//GEN-LAST:event_mitem_consola7ActionPerformed

    private void mitem_consola8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola8ActionPerformed
        ejecutar("consola/consola8.exe");
    }//GEN-LAST:event_mitem_consola8ActionPerformed

    private void mitem_consola9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola9ActionPerformed
        ejecutar("consola/consola9.exe");
    }//GEN-LAST:event_mitem_consola9ActionPerformed

    private void mitem_consola10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola10ActionPerformed
        ejecutar("consola/consola10.exe");
    }//GEN-LAST:event_mitem_consola10ActionPerformed

    private void mitem_consola21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola21ActionPerformed
        ejecutar("consola/consola2.1.exe");
    }//GEN-LAST:event_mitem_consola21ActionPerformed

    private void mitem_consola22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola22ActionPerformed
        ejecutar("consola/consola2.2.exe");
    }//GEN-LAST:event_mitem_consola22ActionPerformed

    private void mitem_consola23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola23ActionPerformed
        ejecutar("consola/consola2.3.exe");
    }//GEN-LAST:event_mitem_consola23ActionPerformed

    private void mitem_consola24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola24ActionPerformed
        ejecutar("consola/consola2.4.exe");
    }//GEN-LAST:event_mitem_consola24ActionPerformed

    private void mitem_consola25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola25ActionPerformed
        ejecutar("consola/consola2.5.exe");
    }//GEN-LAST:event_mitem_consola25ActionPerformed

    private void mitem_consola26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola26ActionPerformed
        ejecutar("consola/consola2.6.exe");
    }//GEN-LAST:event_mitem_consola26ActionPerformed

    private void mitem_consola27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola27ActionPerformed
        ejecutar("consola/consola2.7.exe");
    }//GEN-LAST:event_mitem_consola27ActionPerformed

    private void mitem_consola28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola28ActionPerformed
        ejecutar("consola/consola2.8.exe");
    }//GEN-LAST:event_mitem_consola28ActionPerformed

    private void mitem_consola29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola29ActionPerformed
        ejecutar("consola/consola2.9.exe");
    }//GEN-LAST:event_mitem_consola29ActionPerformed

    private void mitem_consola210ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola210ActionPerformed
        ejecutar("consola/consola2.10.exe");
    }//GEN-LAST:event_mitem_consola210ActionPerformed

    private void mitem_consola31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola31ActionPerformed
        ejecutar("consola/consola3.1.exe");
    }//GEN-LAST:event_mitem_consola31ActionPerformed

    private void mitem_consola32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola32ActionPerformed
        ejecutar("consola/consola3.2.exe");
    }//GEN-LAST:event_mitem_consola32ActionPerformed

    private void mitem_consola33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola33ActionPerformed
        ejecutar("consola/consola3.3.exe");
    }//GEN-LAST:event_mitem_consola33ActionPerformed

    private void mitem_consola34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola34ActionPerformed
        ejecutar("consola/consola3.4.exe");
    }//GEN-LAST:event_mitem_consola34ActionPerformed

    private void mitem_consola35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola35ActionPerformed
        ejecutar("consola/consola3.5.exe");
    }//GEN-LAST:event_mitem_consola35ActionPerformed

    private void mitem_consola36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola36ActionPerformed
        ejecutar("consola/consola3.6.exe");
    }//GEN-LAST:event_mitem_consola36ActionPerformed

    private void mitem_consola37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola37ActionPerformed
        ejecutar("consola/consola3.7.exe");
    }//GEN-LAST:event_mitem_consola37ActionPerformed

    private void mitem_consola38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola38ActionPerformed
        ejecutar("consola/consola3.8.exe");
    }//GEN-LAST:event_mitem_consola38ActionPerformed

    private void mitem_consola39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola39ActionPerformed
        ejecutar("consola/consola3.9.exe");
    }//GEN-LAST:event_mitem_consola39ActionPerformed

    private void mitem_consola310ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola310ActionPerformed
        ejecutar("consola/consola3.10.exe");
    }//GEN-LAST:event_mitem_consola310ActionPerformed

    private void mitem_consola41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola41ActionPerformed
        ejecutar("consola/consola4.1.exe");
    }//GEN-LAST:event_mitem_consola41ActionPerformed

    private void mitem_consola42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola42ActionPerformed
        ejecutar("consola/consola4.2.exe");
    }//GEN-LAST:event_mitem_consola42ActionPerformed

    private void mitem_consola43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola43ActionPerformed
        ejecutar("consola/consola4.3.exe");
    }//GEN-LAST:event_mitem_consola43ActionPerformed

    private void mitem_consola44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola44ActionPerformed
        ejecutar("consola/consola4.4.exe");
    }//GEN-LAST:event_mitem_consola44ActionPerformed

    private void mitem_consola45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola45ActionPerformed
        ejecutar("consola/consola4.5.exe");
    }//GEN-LAST:event_mitem_consola45ActionPerformed

    private void mitem_consola46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola46ActionPerformed
        ejecutar("consola/consola4.6.exe");
    }//GEN-LAST:event_mitem_consola46ActionPerformed

    private void mitem_consola47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola47ActionPerformed
        ejecutar("consola/consola4.7.exe");
    }//GEN-LAST:event_mitem_consola47ActionPerformed

    private void miem_consola48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miem_consola48ActionPerformed
        ejecutar("consola/consola4.8.exe");
    }//GEN-LAST:event_miem_consola48ActionPerformed

    private void mitem_consola49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_consola49ActionPerformed
        ejecutar("consola/consola4.9.exe");
    }//GEN-LAST:event_mitem_consola49ActionPerformed

    private void mitem_2botonesdeopcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_2botonesdeopcionActionPerformed
        new botones_opcion().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem_2botonesdeopcionActionPerformed

    private void mitem_4combosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_4combosActionPerformed
        new Combo().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem_4combosActionPerformed

    private void mitem_5listasmodelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_5listasmodelosActionPerformed
        new Cuadro_listas().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem_5listasmodelosActionPerformed

    private void mitem_6combosmodelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_6combosmodelosActionPerformed
        new Combos_modelos().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem_6combosmodelosActionPerformed

    private void mitem_7togglebutonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_7togglebutonsActionPerformed
        new Toggle_butons().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem_7togglebutonsActionPerformed

    private void mitem_8slidersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_8slidersActionPerformed
        new Sliders().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem_8slidersActionPerformed

    private void mitem_9spinnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_9spinnerActionPerformed
        new Spinner().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem_9spinnerActionPerformed

    private void mitem_10barrasdesplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_10barrasdesplaActionPerformed
        new Barras_desplazamiento().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem_10barrasdesplaActionPerformed

    private void mitem_11barramenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_11barramenuActionPerformed
        new barra_menu().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem_11barramenuActionPerformed

    private void mitem_12barraherramientasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_12barraherramientasActionPerformed
        new barra_herramientas().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem_12barraherramientasActionPerformed

    private void mitem_13menuemergenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_13menuemergenteActionPerformed
        new menu_emergente().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem_13menuemergenteActionPerformed

    private void mitem_14filechooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_14filechooserActionPerformed
        new FileChooser().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem_14filechooserActionPerformed

    private void mitem_15panelesdesplazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_15panelesdesplazActionPerformed
        new Paneles().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem_15panelesdesplazActionPerformed

    private void mitem_16variablesglobalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_16variablesglobalesActionPerformed
        new Variables_Globales().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem_16variablesglobalesActionPerformed

    private void mitem_17centralizarcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_17centralizarcodigoActionPerformed
        new Centralizar_codigo().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem_17centralizarcodigoActionPerformed

    private void mitem18_layoutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem18_layoutsActionPerformed
        new Layouts().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem18_layoutsActionPerformed

    private void mitem_19layoutsypanelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_19layoutsypanelesActionPerformed
        new Layouts_paneles().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem_19layoutsypanelesActionPerformed

    private void mitem_20dialogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_20dialogosActionPerformed
        new Cuadro_dialogo().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitem_20dialogosActionPerformed

    private void mitemcambiarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemcambiarUsuarioActionPerformed
        new Login().setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_mitemcambiarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_secundario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_secundario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_secundario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_secundario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_secundario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barramenusecundario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu jmenu1pdf;
    private javax.swing.JMenu jmenu2pdf;
    private javax.swing.JMenu jmenu3pdf;
    private javax.swing.JMenu jmenu4pdf;
    private javax.swing.JMenu jmenuConsola;
    private javax.swing.JMenu jmenuJFrame;
    private javax.swing.JMenu jmenuJframeIIpdf;
    private javax.swing.JMenu jmenuJframeIpdf;
    private javax.swing.JMenu jmenuJframepdf;
    private javax.swing.JMenu jmenuMateriales;
    private javax.swing.JMenu jmenuSalir;
    private javax.swing.JMenu jmenuUsuario;
    private javax.swing.JMenuItem miem_consola48;
    private javax.swing.JMenuItem mitem18_layouts;
    private javax.swing.JMenuItem mitem_10barrasdespla;
    private javax.swing.JMenuItem mitem_11barramenu;
    private javax.swing.JMenuItem mitem_12barraherramientas;
    private javax.swing.JMenuItem mitem_13menuemergente;
    private javax.swing.JMenuItem mitem_14filechooser;
    private javax.swing.JMenuItem mitem_15panelesdesplaz;
    private javax.swing.JMenuItem mitem_16variablesglobales;
    private javax.swing.JMenuItem mitem_17centralizarcodigo;
    private javax.swing.JMenuItem mitem_19layoutsypaneles;
    private javax.swing.JMenuItem mitem_1cuadrosverificacion;
    private javax.swing.JMenuItem mitem_20dialogos;
    private javax.swing.JMenuItem mitem_2botonesdeopcion;
    private javax.swing.JMenuItem mitem_3listas;
    private javax.swing.JMenuItem mitem_4combos;
    private javax.swing.JMenuItem mitem_5listasmodelos;
    private javax.swing.JMenuItem mitem_6combosmodelos;
    private javax.swing.JMenuItem mitem_7togglebutons;
    private javax.swing.JMenuItem mitem_8sliders;
    private javax.swing.JMenuItem mitem_9spinner;
    private javax.swing.JMenuItem mitem_consola1;
    private javax.swing.JMenuItem mitem_consola10;
    private javax.swing.JMenuItem mitem_consola2;
    private javax.swing.JMenuItem mitem_consola21;
    private javax.swing.JMenuItem mitem_consola210;
    private javax.swing.JMenuItem mitem_consola22;
    private javax.swing.JMenuItem mitem_consola23;
    private javax.swing.JMenuItem mitem_consola24;
    private javax.swing.JMenuItem mitem_consola25;
    private javax.swing.JMenuItem mitem_consola26;
    private javax.swing.JMenuItem mitem_consola27;
    private javax.swing.JMenuItem mitem_consola28;
    private javax.swing.JMenuItem mitem_consola29;
    private javax.swing.JMenuItem mitem_consola3;
    private javax.swing.JMenuItem mitem_consola31;
    private javax.swing.JMenuItem mitem_consola310;
    private javax.swing.JMenuItem mitem_consola32;
    private javax.swing.JMenuItem mitem_consola33;
    private javax.swing.JMenuItem mitem_consola34;
    private javax.swing.JMenuItem mitem_consola35;
    private javax.swing.JMenuItem mitem_consola36;
    private javax.swing.JMenuItem mitem_consola37;
    private javax.swing.JMenuItem mitem_consola38;
    private javax.swing.JMenuItem mitem_consola39;
    private javax.swing.JMenuItem mitem_consola4;
    private javax.swing.JMenuItem mitem_consola41;
    private javax.swing.JMenuItem mitem_consola42;
    private javax.swing.JMenuItem mitem_consola43;
    private javax.swing.JMenuItem mitem_consola44;
    private javax.swing.JMenuItem mitem_consola45;
    private javax.swing.JMenuItem mitem_consola46;
    private javax.swing.JMenuItem mitem_consola47;
    private javax.swing.JMenuItem mitem_consola49;
    private javax.swing.JMenuItem mitem_consola5;
    private javax.swing.JMenuItem mitem_consola6;
    private javax.swing.JMenuItem mitem_consola7;
    private javax.swing.JMenuItem mitem_consola8;
    private javax.swing.JMenuItem mitem_consola9;
    private javax.swing.JMenuItem mitem_jf_10pdf;
    private javax.swing.JMenuItem mitem_jf_11pdf;
    private javax.swing.JMenuItem mitem_jf_12pdf;
    private javax.swing.JMenuItem mitem_jf_13pdf;
    private javax.swing.JMenuItem mitem_jf_14pdf;
    private javax.swing.JMenuItem mitem_jf_15pdf;
    private javax.swing.JMenuItem mitem_jf_16pdf;
    private javax.swing.JMenuItem mitem_jf_17pdf;
    private javax.swing.JMenuItem mitem_jf_18pdf;
    private javax.swing.JMenuItem mitem_jf_19pdf;
    private javax.swing.JMenuItem mitem_jf_1pdf;
    private javax.swing.JMenuItem mitem_jf_20pdf;
    private javax.swing.JMenuItem mitem_jf_2pdf;
    private javax.swing.JMenuItem mitem_jf_3pdf;
    private javax.swing.JMenuItem mitem_jf_4pdf;
    private javax.swing.JMenuItem mitem_jf_5pdf;
    private javax.swing.JMenuItem mitem_jf_6pdf;
    private javax.swing.JMenuItem mitem_jf_7pdf;
    private javax.swing.JMenuItem mitem_jf_8pdf;
    private javax.swing.JMenuItem mitem_jf_9pdf;
    private javax.swing.JMenuItem mitem_salir;
    private javax.swing.JMenuItem mitemcambiarUsuario;
    private javax.swing.JPopupMenu.Separator separador;
    // End of variables declaration//GEN-END:variables
}
